1911061027_DoTrongThuong_BigSchool/Controllers/Api/CoursesController.cs
using _1911061027_DoTrongThuong_BigSchool.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace _1911061027_DoTrongThuong_BigSchool.Controllers.Api
{
    public class CoursesController : ApiController
    {
        public ApplicationDbContext _dbContext { get; set; }

        public CoursesController()
        {
            _dbContext = new ApplicationDbContext();
        }

        [HttpDelete]
        public IHttpActionResult Cancel (int id)
        {
            var userId = User.Identity.GetUserId();
            var course = _dbContext.Courses.Single(c => c.Id == id && c.LecturerId == userId);

            if (course.IsCanceled)
                return NotFound();

            course.IsCanceled = true;
            _dbContext.SaveChanges();

            return Ok();
        }

        [HttpPost]
        public IHttpActionResult Show(int id)
        {
            var userId = User.Identity.GetUserId();
            var course = _dbContext.Courses.Single(c => c.Id == id && c.LecturerId == userId);

            if (!course.IsCanceled)
                return NotFound();

            course.IsCanceled = false;
            _dbContext.SaveChanges();

            return Ok();
        }
    }
}

1911061027_DoTrongThuong_BigSchool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - BigSchool</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
   
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        @Html.ActionLink("BigSchool", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Add Course", "Create", "Courses", new { area = "" }, htmlAttributes: new { @class = "nav-link" })
                    <span class="sr-only">(current)</span>
                </li>
            </ul>
            
            <form action="@Url.Action("Index","Home")" method="post" class="form-inline my-2 my-lg-0">
                @Html.TextBox("search", null, new { @class = "form-control mr-sm-2", name = "Course", placeholder = "Search Course...", required = "" })
               @* <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">*@
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

            </form>
            
            <ul class="navbar-nav ml-1">
                <li class="nav-item active">
                    @Html.Partial("_LoginPartial")
                </li>
            </ul>

        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - BigSchool</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>